---
- name: print effective user
  hosts: allnodes
  #become: yes
  #remote_user: automation
  tasks:
    - name: debug effective user
      debug:
        msg: "{{ ansible_facts['user_id'] }}"

#   - name: test become privilege
#     command:
#       cmd: cat /etc/shadow
#     register: shadow

#   - name: show shadow
#     debug:
#       msg: "{{ shadow }}"
