---
- name: test localhost here
  hosts: localhost
  become: no
  tasks:
    - name: run hostname cmd
      command: hostname
    - name: run id
      command: id

- name: test allnodes here
  hosts: allnodes
  become: no
  tasks:
    - name: run hostname cmd
      command: hostname
    - name: run id
      command: id
