---
- name: play with secret
  hosts: allnodes
  become: yes
  remote_user: automation
  vars_files:
    - secrets.yml
  tasks:
    - name: create new user with vars from file
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
        update_password: on_create
        state: present
    
    
    - name: print actual remote_user
      debug:
        msg: "{{ ansible_facts['user_id'] }}"
